
#CREO LA PRIMER CLASE MAMIFERO
class Mamifero
  #CREO SU METODO RESPIRAR
  def respirar
    puts 'Respirar'
  end
end

#CREO AL CLASE GATO QUE HEREDA LA CLASE MAMIFERO, LA HEREDA USANDO EL SIMBOLO DE <
class Gato < Mamifero
  #CREO EL METOOD MAULLAR
  def maullar
    puts 'Maullando'
  end
end

#GENERO UN NUEVO OBJETO DE LA CLASE GATO
gato= Gato.new

#LA CLASE GATO ES POSEEDORA DEL METODO MAULLAR
puts 'CLASE GATO ES DUENA DE LA CLASE MAULLAR LA INVOCO:OK:'
puts gato.maullar
#LA CLASE GATO HERADA EL METODO RESPIRAR DE LA CLASE MAMIFERO
puts 'CLASE RESPIRAR ES DE LA CLASE MAMIFERO PERO ES HEREDADA A LA CLASE GATO'
puts gato.respirar
